## Principal diferença entre acesso a matriz: Matlab → Python
   A principal diferença está no acesso a **colunas**
   
   **Não vi isso explícito em nenhum site**
   
   ___
   
   Gerando uma matriz  
   (números inteiros aleatórios de 0 a 10, 8 linhas, 5 colunas)

In [1]:
from numpy import *
A = random.randint(0,10,(8,5))
A

array([[0, 0, 5, 1, 6],
       [6, 5, 0, 1, 6],
       [8, 8, 3, 1, 9],
       [7, 7, 0, 6, 9],
       [6, 8, 0, 5, 8],
       [3, 2, 8, 6, 0],
       [9, 9, 3, 5, 3],
       [8, 0, 7, 9, 4]])

___
Usando a mesma matriz no Matlab:
```
--> A =[0, 0, 5, 1, 6;
  >     6, 5, 0, 1, 6;
  >     8, 8, 3, 1, 9;
  >     7, 7, 0, 6, 9;
  >     6, 8, 0, 5, 8;
  >     3, 2, 8, 6, 0;
  >     9, 9, 3, 5, 3;
  >     8, 0, 7, 9, 4]
  
 A  =

   0.   0.   5.   1.   6.
   6.   5.   0.   1.   6.
   8.   8.   3.   1.   9.
   7.   7.   0.   6.   9.
   6.   8.   0.   5.   8.
   3.   2.   8.   6.   0.
   9.   9.   3.   5.   3.
   8.   0.   7.   9.   4.
```
___
### Acesso a uma submatriz no Matlab:  
Exemplo: Linhas 3 até a 5, coluna 2 até a 4
```
--> A(3:5,2:4)
 ans  =

   8.   3.   1.
   7.   0.   6.
   8.   0.   5.
```
___
### Acessando a mesma submatriz no Python.
* Usar `[]` ao invéz de `()`
* Como é 'zero-based', a linha `3` vira a linha `2`
* A linha `5` vira a linha `4`, pelo mesmo motivo.
* Porém, com o último índice é 'exclusive', para ir até a linha `4`, usa-se a linha `5` mesmo
* Mesmo acontece para coluna: `(2:4)` vira `[1:4]`

In [2]:
A[2:5,1:4]

array([[8, 3, 1],
       [7, 0, 6],
       [8, 0, 5]])

___
### Acessando uma linha no Matlab

Exemplo: linha `4`

```
--> A(4,:)
 ans  =

   7.   7.   0.   6.   9.

```
Notar que o vetor-linha final tem 2 dimensões
```
--> size(ans)
 ans  =   

   1.   5.
```
___
### Acessando a mesma linha no Python
Linha `4` terá índice `3`

In [3]:
A[3,:]

array([7, 7, 0, 6, 9])

**Porém**, atentar que este vetor-final tem 1 dimensão

In [4]:
shape(A[3,:])

(5,)

Ou seja, transpor a linha não altera nada

In [5]:
transpose(A[3,:])

array([7, 7, 0, 6, 9])

___
### Acessando a linha com duas dimensões (como ocorre no Matlab):
Para acessar o vetor anterior com **duas** dimensões, há duas formas:
1. Selecionar o índice ``3`` como uma *lista* (objeto iterável): ``[3]``
2. Selecionar o índice ``3`` como uma *Slice*: ``3:4`` (acaba que também é um objeto iterável)

No segundo caso, o índice vai de **``3`` até ``4`` exclusive**, ou seja, vai de ``3`` até ``3``,  
selecionando, assim, a linha ``3`` (que equivale à linha ``4``, pois é 'zero-based')

#### Exemplo de uso do caso (1.)

In [6]:
A[[3],:]

array([[7, 7, 0, 6, 9]])

#### Exemplo de uso do caso (2.)

In [7]:
A[3:4,:]

array([[7, 7, 0, 6, 9]])

Notar que as respostas estão dentro de ``[[ ]]``, e não somente de ``[ ]``, mostrando que agora temos uma matriz de 2 dimensões, igual no Matlab

In [8]:
shape(A[[3],:]) # Caso (1.)

(1, 5)

In [9]:
shape(A[3:4,:]) # Caso (2.)

(1, 5)

Isso fica mais evidente ao tentar acessar colunas
___
### Acessando uma coluna no Matlab
Exemplo: coluna ``3``
```
--> A(:,3)
 ans  =

   5.
   0.
   3.
   0.
   0.
   8.
   3.
   7.

--> size(ans)
 ans  =

   8.   1.
 ```
 ___
### Acessando da mesma coluna no Python 
Coluna `3` vira índice `2`

In [10]:
A[:,2]

array([5, 0, 3, 0, 0, 8, 3, 7])

Encontra-se novamente um vetor de 1 dimensão (só um ``[ ]``)

In [11]:
shape(A[:,2])

(8,)

Mas fazendo o índice igual à variável **linha ``[2]``** ou como o **slice ``2:3``** (``2`` até ``3`` **exclusive**, ou seja, de ``2`` até ``2``)  
Tem-se o mesmo resultado do Matlab (coluna ``3`` da matriz)

In [12]:
A[:,[2]] # Caso (1.)

array([[5],
       [0],
       [3],
       [0],
       [0],
       [8],
       [3],
       [7]])

In [13]:
shape(A[:,[2]])

(8, 1)

In [14]:
A[:,2:3] # Caso (2.)

array([[5],
       [0],
       [3],
       [0],
       [0],
       [8],
       [3],
       [7]])

In [15]:
shape(A[:,2:3])

(8, 1)

___
### Objeto Matrix
Existe ainda o objeto 'Matrix' no Numpy, que se comporta como uma matriz do Matlab  
Este objeto pode ser criado a partir de um array

In [16]:
M = matrix(A)
M

matrix([[0, 0, 5, 1, 6],
        [6, 5, 0, 1, 6],
        [8, 8, 3, 1, 9],
        [7, 7, 0, 6, 9],
        [6, 8, 0, 5, 8],
        [3, 2, 8, 6, 0],
        [9, 9, 3, 5, 3],
        [8, 0, 7, 9, 4]])

O acesso aos elementos se dá mais parecido com o Matlab.  
A coluna anterior, por exemplo (coluna `3`), se acessa da seguinte forma:

In [17]:
M[:,2]

matrix([[5],
        [0],
        [3],
        [0],
        [0],
        [8],
        [3],
        [7]])

___
Porém, como indicado nesta página:

https://numpy.org/devdocs/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use  

É mais recomendado continuar usando o obejto array